[web]
  title = "Heimdall"
  port = 8910
  apiUrl = "/.redwood/functions"
  includeEnvironmentVariables = ["CLERK_PUBLISHABLE_KEY"]
[api]
  port = 8911
[browser]
  open = false
[notifications]
  versionUpdates = ["latest"]
